version: '3.2'
services:
  database:
    container_name: talk-db
    image: mysql/mysql-server:latest
    env_file: database/variables.env
    expose:
      - "3306" # port available to other docker containers but not host network
    volumes:
      - type: bind
        source: ./database/scripts/
        target: /docker-entrypoint-initdb.d/
      - database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  express:
    depends_on:
      - "database"
    container_name: talk-js
    env_file: database/variables.env
    build: 
      context: ./server
      dockerfile: Dockerfile-dev
    volumes:
      - ./server/assets:/usr/src/app/assets
      - ./server/home:/usr/src/app/home
      - ./server/vendor:/usr/src/app/vendor
      - ./server/server.js:/usr/src/app/server.js
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${PORT}:8080"
    tty: true   # COLORS

volumes:
  database: 