version: '3.2'
services:
  database:
    container_name: talk-db
    image: mysql/mysql-server:5.7
    env_file: database/variables.env
    expose:
      - "3306" # port available to other docker containers but not host network
    volumes:
      - ./database/scripts/:/docker-entrypoint-initdb.d/:Z # Z access mode - use private unshared label to accommodate for SELinux polcy
      - database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  express:
    depends_on:
      - "database"
    container_name: talk-js
    env_file: database/variables.env
    build: ./server
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${PORT}:8080"
    tty: true   # COLORS

volumes:
  database: